//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examination_system.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Std_Crs = new HashSet<Std_Crs>();
            this.Std_Ques_Exm = new HashSet<Std_Ques_Exm>();
        }
    
        public int Std_Id { get; set; }
        public Nullable<int> U_Id { get; set; }
        public Nullable<int> Dept_Id { get; set; }
        public string Std_Fname { get; set; }
        public string Std_Lname { get; set; }
        public Nullable<System.DateTime> Std_BOD { get; set; }
        public string Std_Address { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Std_Crs> Std_Crs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Std_Ques_Exm> Std_Ques_Exm { get; set; }
        public virtual User User { get; set; }
    }
}
